name: Deploy documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "docs/**"
jobs:
  update-gh-pages:
    name: Generate and upload new documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run action
        uses: ldeluigi/markdown-docs@v0
        with:
          src: docs/
          dst: ./gh-pages
          title:  AxolotlEditorDocs
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./gh-pages
